T1 = ()
L1 = list(T1)
n1 = int(input('Enter 1st number : '))
n2 = int(input('Enter 2nd number : '))
n3 = int(input('Enter 3rd number : '))
n4 = int(input('Enter 4th number : '))
n5 = int(input('Enter 5th number : '))
n6 = int(input('Enter 6th number : '))
L1.append(n1)
L1.append(n2)
L1.append(n3)
L1.append(n4)
L1.append(n5)
L1.append(n6)
T2 = tuple(L1)
add = sum(T2)
print("The final tuple is : " + str(T2))
print("The sum of all the elements of the tuple is : " + str(add))